### ISSUE TITLE
Not working!!

### ISSUE THREAD

**Issue by AnilRana675** [fhuhne/CR-Unblocker#15] opened 2022-10-22 04:33 UTC
Please update...

**Comment by fhuhne** [comment] 2022-10-22 08:04
Hi, it is working fine for me. Do you get any kind of error?

**Comment by AnilRana675** [comment] 2022-10-22 08:10
> Hi, it is working fine for me. Do you get any kind of error?

Yeah, I didn't get some anime like chainsaw Man,nisekoi etc which is block on my country.

**Comment by AnilRana675** [comment] 2022-10-22 08:12
I am using brave browsers.

**Comment by fhuhne** [comment] 2022-10-22 08:20
Sorry I don't officially support any browsers besides Firefox. Are you on Version 3.0 of the extension? This is required for the new Crunchyroll site.

**Comment by AnilRana675** [comment] 2022-10-22 08:34
> Sorry I don't officially support any browsers besides Firefox. Are you on Version 3.0 of the extension? This is required for the new Crunchyroll site.

Yeah, I am using latest version. 
Recently I tested on Firefox. It works but not working on chromium browsers.

**Comment by AnilRana675** [comment] 2022-10-22 09:01
I have problem with crunchyroll IFrame player. It always loading. IFrame player works when I disable cr-unblocker but I need bypass block from crunchyroll. What can I do??

**Comment by fhuhne** [comment] 2023-02-20 19:51
I'm closing this as I kinda forgot these issues. Sorry for the missing reply - I can't really help with issues caused by other extensions as they change the browser behavior in different ways and supporting them would be more work. I'm open for contributions though, if someone wants to improve compatibility.

**Closed by fhuhne** 2023-02-20 19:51 UTC
